#!/usr/bin/env python

#Instructions - Create a plot of a parabola (e.g. y = x^2)
#Let's do the simple case first, where the vector x is defined and then we square each value to create a vector for y.  The two vectors will be plotted against each other.

# Enter these two commands if start a new workspace:
#sudo easy_install numpy
#sudo easy_install matplotlib

from scipy.optimize import fmin
import numpy as np
import math
import sys
import matplotlib
matplotlib.use('Agg') #This is required to run matplotlib on Google Chrome.
import matplotlib.pyplot as plt

# Make a vector of numbers from 0 to 1000
x = np.asarray(range(0,100000))/100.
print x

# A function 
def func(x):
    return (x**2) 
#def allows you to define a function of your own, in this case a function of x
#x**2 means "x-squared"

# Forward problem: given x compute func(x)
# The value of our function at 1
print 'Here is our function at 1: ' + str(func(1.))
#one squared should be one

# Let's try it with another value:
# The value of our function at 5
print 'Here is our function at 5: ' + str(func(5))
#five squared should be 25.
